# No 1

In [8]:
# Perkalian Matrix
# TTL   : 07 April 2003
# No Hp : 085830027214

import numpy as np

A = np.array([[0,7],[0,4],[0,3]])
B = np.array([[0,2],[7,2],[1,4]])

kali = A * B
print(kali)

[[ 0 14]
 [ 0  8]
 [ 0 12]]


# No 2

In [9]:
# Pengurangan Matrix

import numpy as np

A = np.array([[0,7],[0,4],[0,3]])
B = np.array([[0,2],[7,2],[1,4]])

kurang = A - B
print(kurang)

[[ 0  5]
 [-7  2]
 [-1 -1]]


# No 3

In [11]:
# Transpose Matrix

import numpy as np

A = np.array([[0,7],[0,4],[0,3]])
B = np.array([[0,2],[7,2],[1,4]])

transpose_A = np.transpose(A)
transpose_B = np.transpose(B)

print(transpose_A)
print(transpose_B)

[[0 0 0]
 [7 4 3]]
[[0 7 1]
 [2 2 4]]


# No 4

In [21]:
# Nilai Invers


import numpy as np

A = np.array([[1,9],[0,6]])
B = np.array([[1,4],[7,0]])


invers_A = np.linalg.inv(A)
invers_B = np.linalg.inv(B)

print("\nInvers matrix A :")
print("\nInvers matrix B :")
print(invers_A)
print(invers_B)



Invers matrix A :

Invers matrix B :
[[ 1.         -1.5       ]
 [ 0.          0.16666667]]
[[ 0.          0.14285714]
 [ 0.25       -0.03571429]]


# No 5

In [24]:
# Nilai Determinan

import numpy as np

A = np.array([[0,7],[0,4]])
B = np.array([[0,2],[7,2]])

determinant_A = np.linalg.det(A)
determinant_B = np.linalg.det(B)
print("Determinan dari matrix A:", determinant_A)
print("Determinan dari matrix B:", determinant_B)

Determinan dari matrix A: 0.0
Determinan dari matrix B: -13.999999999999996
